column_rename_map_2013 = {
    "What Country or Region do you live in?" : "Country",
    "Which US State or Territory do you live in?" : "USState",
    "How old are you?" : "Age",
    "How many years of IT/Programming experience do you have?" : "YearsProgram",
    "How would you best describe the industry you currently work in?" : "Industry",
    "How many people work for your company?" : "CompanySize",
    "Which of the following best describes your occupation?" : "Occupation",
    "Including yourself, how many developers are employed at your company?" : "NumDevsAtCompany",
    "How large is the team that you work on?" : "SizeOfTeam",
    "What other departments / roles do you interact with regularly?" : "InteractWithSysAdm",
    "Unnamed: 10" : "InteractWithDesigners",
    "Unnamed: 11" : "InteractWithProdMgr",
    "Unnamed: 12" : "InteractWithQA",
    "Unnamed: 13" : "InteractWithTechSupport",
    "Unnamed: 14" : "InteractWithSales",
    "Unnamed: 15" : "InteractWithConsultants",
    "Unnamed: 16" : "InteractWithCustomers",
    "Unnamed: 17" : "InteractWithFinance",
    "Unnamed: 18" : "InteractWithHR",
    "If your company has a native mobile app, what platforms do you support?" : "AppSuppiPhone",
    "Unnamed: 20" : "AppSuppiPad",
    "Unnamed: 21" : "AppSuppAndroidPhone",
    "Unnamed: 22" : "AppSuppAndroidTablet",
    "Unnamed: 23" : "AppSuppBlackberry",
    "Unnamed: 24" : "AppSuppOther",
    "Unnamed: 25" : "AppSuppNoMobile",
    "If you make a software product, how does your company make money? (You can choose more than one)" : "CompRevSourceAds",
    "Unnamed: 27" : "CompRevSourceDirSalesCust",
    "Unnamed: 28" : "CompRevSourceDirSalesCompanies",
    "Unnamed: 29" : "CompRevSourceSaaS",
    "Unnamed: 30" : "CompRevSourceMobilApps",
    "Unnamed: 31" : "CompRevSourceConsulting",
    "Unnamed: 32" : "CompRevSourceGrants",
    "Unnamed: 33" : "CompRevSourceOther",
    "In an average week, how do you spend your time?" : "SpendTimeOnNewFeatures",
    "Unnamed: 35" : "SpendTimeOnRefactoring",
    "Unnamed: 36" : "SpendTimeOnBugFixes",
    "Unnamed: 37" : "SpendTimeOnTechSupp",
    "Unnamed: 38" : "SpendTimeOnMeetings",
    "Unnamed: 39" : "SpendTimeOnNewSkills",
    "Unnamed: 40" : "SpendTimeOnInternet",
    "Unnamed: 41" : "SpendTimeOnCommute",
    "What is your involvement in purchasing products or services for the company you work for? (You can choose more than one)" : "ProdPurchRoleRecommend",
    "Unnamed: 43" : "ProdPurchRoleInfluence",
    "Unnamed: 44" : "ProdPurchRoleBudget",
    "Unnamed: 45" : "ProdPurchRoleUnlimited",
    "Unnamed: 46" : "ProdPurchRoleWriteChecks",
    "Unnamed: 47" : "ProdPurchRoleNone",
    "Unnamed: 48" : "ProdPurchRoleSeller",
    "What types of purchases are you involved in?" : "ProdPurchTypeHardware",
    "Unnamed: 50" : "ProdPurchTypeServers",
    "Unnamed: 51" : "ProdPurchTypeSoftware",
    "Unnamed: 52" : "ProdPurchTypeUserEquip",
    "Unnamed: 53" : "ProdPurchTypeConsultants",
    "Unnamed: 54" : "ProdPurchTypeOther",
    "What is your budget for outside expenditures (hardware, software, consulting, etc) for 2013?" : "OutsideExpenseBudget",
    "Which of the following languages or technologies have you used significantly in the past year?" : "ProgLangUsedC",
    "Unnamed: 57" : "ProgLangUsedC++",
    "Unnamed: 58" : "ProgLangUsedC#",
    "Unnamed: 59" : "ProgLangUsedJava",
    "Unnamed: 60" : "ProgLangUsedJavaScript",
    "Unnamed: 61" : "ProgLangUsedjQuery",
    "Unnamed: 62" : "ProgLangUsedJQuery",
    "Unnamed: 63" : "ProgLangUsedNode.js",
    "Unnamed: 64" : "ProgLangUsedObjective-C",
    "Unnamed: 65" : "ProgLangUsedPHP",
    "Unnamed: 66" : "ProgLangUsedPython",
    "Unnamed: 67" : "ProgLangUsedRuby",
    "Unnamed: 68" : "ProgLangUsedSQL",
    "Unnamed: 69" : "ProgLangUsedOther",
    "Which technologies are you excited about?" : "TechExcitedAbtNode.js",
    "Unnamed: 71" : "TechExcitedAbtHaskell",
    "Unnamed: 72" : "TechExcitedAbtCoffeeScript",
    "Unnamed: 73" : "TechExcitedAbtDart",
    "Unnamed: 74" : "TechExcitedAbtTypeScript",
    "Unnamed: 75" : "TechExcitedAbtC++11",
    "Unnamed: 76" : "TechExcitedAbtWinRT",
    "Unnamed: 77" : "TechExcitedAbtRedis",
    "Unnamed: 78" : "TechExcitedAbtMongoDB",
    "Unnamed: 79" : "TechExcitedAbtF#",
    "Unnamed: 80" : "TechExcitedAbtPhoneGap",
    "Which desktop operating system do you use the most?" : "DesktopOS",
    '''Please rate how important each of the following characteristics of a company/job offer are to you.    Please select a MAXIMUM of 3 items as "Non-Negotiables" to help us identify the most important items, those where you would never consider a company if they didn't meet them.''' : "JobImprtncBaseSalary",
    "Unnamed: 83" : "JobImprtncStockOpt",
    "Unnamed: 84" : "JobImprtncCompGoals",
    "Unnamed: 85" : "JobImprtncCompProd",
    "Unnamed: 86" : "JobImprtncLrningOppor",
    "Unnamed: 87" : "JobImprtncSkillGrwth",
    "Unnamed: 88" : "JobImprtncQualOffSpce",
    "Unnamed: 89" : "JobImprtncQualTeam",
    "Unnamed: 90" : "JobImprtncPosOrgStrc",
    "Unnamed: 91" : "JobImprtncCntrlOfOwnWrk",
    "Unnamed: 92" : "JobImprtncQualWrkstn",
    "Unnamed: 93" : "JobImprtncBudgAutonomy",
    "Unnamed: 94" : "JobImprtncOffcCity",
    "Unnamed: 95" : "JobImprtncConvCommute",
    "Unnamed: 96" : "JobImprtnc40HrWk",
    "Unnamed: 97" : "JobImprtncLtdNightWkndWork",
    "Have you changed jobs in the last 12 months?" : "ChangedJobsInLastYear",
    "What best describes your career / job satisfaction?" : "CareerJobSatisfaction",
    "Including bonus, what is your annual compensation in USD?" : "TotalCompensation",
    "Which technology products do you own? (You can choose more than one)" : "TechOwnediPhone",
    "Unnamed: 102" : "TechOwnedAndroid",
    "Unnamed: 103" : "TechOwnedBlackberry",
    "Unnamed: 104" : "TechOwnedWinPhone",
    "Unnamed: 105" : "TechOwnediPad",
    "Unnamed: 106" : "TechOwnedAndrTablet",
    "Unnamed: 107" : "TechOwnedKindleFire",
    "Unnamed: 108" : "TechOwnedWinTablet",
    "Unnamed: 109" : "TechOwnedKindle",
    "Unnamed: 110" : "TechOwnedNook",
    "Unnamed: 111" : "TechOwnedPS3",
    "Unnamed: 112" : "TechOwnedXbox",
    "Unnamed: 113" : "TechOwnedWii",
    "Unnamed: 114" : "TechOwnedOther",
    "In the last 12 months, how much money have you spent on personal technology-related purchases?" : "AmtSpentOnTechLastYr",
    "Please rate the advertising you've seen on Stack Overflow" : "StckOvrflwAdsRelevant",
    "Unnamed: 117" : "StckOvrflwAdsEntertaining",
    "Unnamed: 118" : "StckOvrflwAdsInformative",
    "Unnamed: 119" : "StckOvrflwAdsClickThruIntrstingAds",
    "Unnamed: 120" : "StckOvrflwAdsPurchasedProduct",
    "Unnamed: 121" : "StckOvrflwAdsUseAdBlocker",
    "What advertisers do you remember seeing on Stack Overflow?" : "StckOvrflwAdsRemembered",
    "What is your current Stack Overflow reputation?" : "StckOvrflwReputation",
    "How do you use Stack Overflow?" : "StckOvrflwUseReadOthrQs",
    "Unnamed: 125" : "StckOvrflwUseAskQs",
    "Unnamed: 126" : "StckOvrflwUseAnsQs",
    "Unnamed: 127" : "StckOvrflwUseOther"
}

column_rename_map_2014 = {
    "What Country do you live in?" : "Country",
    "Unnamed: 1" : "CountryOther",
    "Which US State or Territory do you live in?" : "USState",
    "How old are you?" : "Age",
    "What is your gender?" : "Gender",
    "How many years of IT/Programming experience do you have?" : "YearsProgram",
    "Which of the following best describes your occupation?" : "Occupation",
    "Including bonus, what is your annual compensation in USD?" : "TotalCompensation",
    "How would you best describe the industry you currently work in?" : "Industry",
    "How many developers are employed at your company?" : "NumDevsAtCompany",
    "Do you work remotely?" : "WorkRemotely",
    "Do you enjoy working remotely?" : "EnjoyWorkRemotely",
    "Where do you work remotely most of the time?" : "WhereWorkRemotely",
    "If your company has a native mobile app, what platforms do you support?" : "AppSuppiPhone",
    "Unnamed: 14" : "AppSuppiPad",
    "Unnamed: 15" : "AppSuppAndroidPhone",
    "Unnamed: 16" : "AppSuppAndroidTablet",
    "Unnamed: 17" : "AppSuppWinPhone",
    "Unnamed: 18" : "AppSuppOther",
    "Unnamed: 19" : "AppSuppNoMobile",
    "In an average week, how do you spend your time at work?" : "SpendTimeOnNewFeatures",
    "Unnamed: 21" : "SpendTimeOnRefactoring",
    "Unnamed: 22" : "SpendTimeOnBugFixes",
    "Unnamed: 23" : "SpendTimeOnTechSupp",
    "Unnamed: 24" : "SpendTimeOnMeetings",
    "Unnamed: 25" : "SpendTimeOnNewSkills",
    "Unnamed: 26" : "SpendTimeOnInternet",
    "Unnamed: 27" : "SpendTimeOnJobSearch",
    "Unnamed: 28" : "SpendTimeOnStackExch",
    "What is your involvement in purchasing products or services for the company you work for? (You can choose more than one)" : "ProdPurchRoleRecommend",
    "Unnamed: 30" : "ProdPurchRoleInfluence",
    "Unnamed: 31" : "ProdPurchRoleBudget",
    "Unnamed: 32" : "ProdPurchRoleUnlimited",
    "Unnamed: 33" : "ProdPurchRoleNone",
    "What types of purchases are you involved in?" : "ProdPurchTypeHardware",
    "Unnamed: 35" : "ProdPurchTypeServers",
    "Unnamed: 36" : "ProdPurchTypeSoftware",
    "Unnamed: 37" : "ProdPurchTypeUserEquip",
    "Unnamed: 38" : "ProdPurchTypeConsultants",
    "Unnamed: 39" : "ProdPurchRecruitTools",
    "Unnamed: 40" : "ProdPurchTypeOther",
    "What is your budget for outside expenditures (hardware, software, consulting, etc) for 2014?" : "OutsideExpenseBudget",
    "Which of the following languages or technologies have you used significantly in the past year?" : "ProgLangUsedC",
    "Unnamed: 43" : "ProgLangUsedC++",
    "Unnamed: 44" : "ProgLangUsedC#",
    "Unnamed: 45" : "ProgLangUsedJava",
    "Unnamed: 46" : "ProgLangUsedJavaScript",
    "Unnamed: 47" : "ProgLangUsedNode.js",
    "Unnamed: 48" : "ProgLangUsedObjective-C",
    "Unnamed: 49" : "ProgLangUsedPHP",
    "Unnamed: 50" : "ProgLangUsedPython",
    "Unnamed: 51" : "ProgLangUsedRuby",
    "Unnamed: 52" : "ProgLangUsedSQL",
    "Unnamed: 53" : "ProgLangUsedOther (please specify)",
    "Which technologies are you excited about?" : "TechExcitedAbtNode.js",
    "Unnamed: 55" : "TechExcitedAbtHaskell",
    "Unnamed: 56" : "TechExcitedAbtCoffeeScript",
    "Unnamed: 57" : "TechExcitedAbtDart",
    "Unnamed: 58" : "TechExcitedAbtC++11",
    "Unnamed: 59" : "TechExcitedAbtRedis",
    "Unnamed: 60" : "TechExcitedAbtMongoDB",
    "Unnamed: 61" : "TechExcitedAbtF#",
    "Unnamed: 62" : "TechExcitedAbtPhoneGap",
    "Unnamed: 63" : "TechExcitedAbtHadoop",
    "Unnamed: 64" : "TechExcitedAbtAngularJS",
    "Unnamed: 65" : "TechExcitedAbtCordova",
    "Unnamed: 66" : "TechExcitedAbtRaspPi",
    "Which desktop operating system do you use the most?" : "DesktopOS",
    "Which technology products do you own? (You can choose more than one)" : "TechOwnediPhone",
    "Unnamed: 69" : "TechOwnedAndroid",
    "Unnamed: 70" : "TechOwnedWinPhone",
    "Unnamed: 71" : "TechOwnediPad",
    "Unnamed: 72" : "TechOwnedAndrTablet",
    "Unnamed: 73" : "TechOwnedKindleFire",
    "Unnamed: 74" : "TechOwnedWinTablet",
    "Unnamed: 75" : "TechOwnedPS3",
    "Unnamed: 76" : "TechOwnedPS4",
    "Unnamed: 77" : "TechOwnedXbox360",
    "Unnamed: 78" : "TechOwnedXboxOne",
    "Unnamed: 79" : "TechOwnedWii",
    "Unnamed: 80" : "TechOwnedWiiU",
    "Unnamed: 81" : "TechOwnedOther",
    "Have you changed jobs in the last 12 months?" : "ChangedJobsInLastYear",
    "How did you find out about your current job?" : "HowFindOutCurrJob",
    "Unnamed: 84" : "HowFindOutCurrJobOth",
    "Are you currently looking for a job or open to new opportunities?" : "CurrLookingNewJob",
    "How often are you contacted by recruiters?" : "FreqOfCntctByRecruitrs",
    "How do you prefer to be contacted about job opportunities?" : "JobOppCntctPrefEmail",
    "Unnamed: 88" : "JobOppCntctPrefLinkedIn",
    "Unnamed: 89" : "JobOppCntctPrefPhone",
    "Unnamed: 90" : "JobOppCntctPrefStckOvrfw",
    "Unnamed: 91" : "JobOppCntctPrefTwtr",
    "In receiving an email about a job opportunity, what attributes of the message would make you more likely to respond?" : "JobOppRespToPersMsg",
    "Unnamed: 93" : "JobOppRespToRefsMyCode",
    "Unnamed: 94" : "JobOppRespToSalryInfo",
    "Unnamed: 95" : "JobOppRespToDescMyTeam",
    "Unnamed: 96" : "JobOppRespToDescCompCultr",
    "Unnamed: 97" : "JobOppRespToDescBenefts",
    "Unnamed: 98" : "JobOppRespToLinkToStckOvrflw",
    "How often do you visit job boards?" : "FreqOfJobBoardVisits",
    "Have you visited / Are you aware of Stack Overflow Careers 2.0?" : "AwareOfStckOvrflw2.0",
    "Do you have a Stack Overflow Careers 2.0 Profile?" : "HaveStckOvrflw2.0Profile",
    "Please rate the advertising you've seen on Stack Overflow" : "StckOvrflwAdsRelevant",
    "Unnamed: 103" : "StckOvrflwAdsEntertaining",
    "Unnamed: 104" : "StckOvrflwAdsInformative",
    "Unnamed: 105" : "StckOvrflwAdsClickThruIntrstingAds",
    "Unnamed: 106" : "StckOvrflwAdsPurchasedProduct",
    "Unnamed: 107" : "StckOvrflwAdsFlagUnwntdAds",
    "Unnamed: 108" : "StckOvrflwAdsUseAdBlocker",
    "Were you aware of the Apptivate contest?" : "AwareOfApptivate",
    "Did you participate in the Apptivate contest?" : "ParticipatedInApptivate",
    "What advertisers do you remember seeing on Stack Overflow?" : "StckOvrflwAdsRemembered",
    "What is your current Stack Overflow reputation?" : "StckOvrflwReputation",
    "How do you use Stack Overflow?" : "StckOvrflwUseReadOthrQs",
    "Unnamed: 114" : "StckOvrflwUseAskQs",
    "Unnamed: 115" : "StckOvrflwUseAnsQs",
    "Unnamed: 116" : "StckOvrflwUseJobSearch",
    "Unnamed: 117" : "StckOvrflwUseBuildOnlineRep",
    "Unnamed: 118" : "StckOvrflwUseOther",
    "How often do you find solutions to your programming problems on Stack Overflow without asking a new question?" : "FreqFindQSolnOnStckOvrflw"
}

column_rename_map_2015 = {
"Country" : "Country",
"Age" : "Age",
"Gender" : "Gender",
"Tabs or Spaces" : "TabsOrSpaces",
"Years IT / Programming Experience" : "YearsProgram",
"Occupation" : "Occupation",
"Desktop Operating System" : "DesktopOS",
"Desktop Operating System: write-in" : "DesktopOSWriteIn",
"Current Lang & Tech: Android" : "CurrLangTechAndroid",
"Current Lang & Tech: Arduino" : "CurrLangTechArduino",
"Current Lang & Tech: AngularJS" : "CurrLangTechAngularJS",
"Current Lang & Tech: C" : "CurrLangTechC",
"Current Lang & Tech: C++" : "CurrLangTechC++",
"Current Lang & Tech: C++11" : "CurrLangTechC++11",
"Current Lang & Tech: C#" : "CurrLangTechC#",
"Current Lang & Tech: Cassandra" : "CurrLangTechCassandra",
"Current Lang & Tech: CoffeeScript" : "CurrLangTechCoffeeScript",
"Current Lang & Tech: Cordova" : "CurrLangTechCordova",
"Current Lang & Tech: Clojure" : "CurrLangTechClojure",
"Current Lang & Tech: Cloud" : "CurrLangTechCloud",
"Current Lang & Tech: Dart" : "CurrLangTechDart",
"Current Lang & Tech: F#" : "CurrLangTechF#",
"Current Lang & Tech: Go" : "CurrLangTechGo",
"Current Lang & Tech: Hadoop" : "CurrLangTechHadoop",
"Current Lang & Tech: Haskell" : "CurrLangTechHaskell",
"Current Lang & Tech: iOS" : "CurrLangTechiOS",
"Current Lang & Tech: Java" : "CurrLangTechJava",
"Current Lang & Tech: JavaScript" : "CurrLangTechJavaScript",
"Current Lang & Tech: LAMP" : "CurrLangTechLAMP",
"Current Lang & Tech: Matlab" : "CurrLangTechMatlab",
"Current Lang & Tech: MongoDB" : "CurrLangTechMongoDB",
"Current Lang & Tech: Node.js" : "CurrLangTechNode.js",
"Current Lang & Tech: Objective-C" : "CurrLangTechObjective-C",
"Current Lang & Tech: Perl" : "CurrLangTechPerl",
"Current Lang & Tech: PHP" : "CurrLangTechPHP",
"Current Lang & Tech: Python" : "CurrLangTechPython",
"Current Lang & Tech: R" : "CurrLangTechR",
"Current Lang & Tech: Redis" : "CurrLangTechRedis",
"Current Lang & Tech: Ruby" : "CurrLangTechRuby",
"Current Lang & Tech: Rust" : "CurrLangTechRust",
"Current Lang & Tech: Salesforce" : "CurrLangTechSalesforce",
"Current Lang & Tech: Scala" : "CurrLangTechScala",
"Current Lang & Tech: Sharepoint" : "CurrLangTechSharepoint",
"Current Lang & Tech: Spark" : "CurrLangTechSpark",
"Current Lang & Tech: SQL" : "CurrLangTechSQL",
"Current Lang & Tech: SQL Server" : "CurrLangTechSQLServer",
"Current Lang & Tech: Swift" : "CurrLangTechSwift",
"Current Lang & Tech: Visual Basic" : "CurrLangTechVisualBasic",
"Current Lang & Tech: Windows Phone" : "CurrLangTechWindowsPhone",
"Current Lang & Tech: Wordpress" : "CurrLangTechWordpress",
"Current Lang & Tech: Write-In" : "CurrLangTechWrite-In",
"Future Lang & Tech: Android" : "FutureLangTechAndroid",
"Future Lang & Tech: Arduino" : "FutureLangTechArduino",
"Future Lang & Tech: AngularJS" : "FutureLangTechAngularJS",
"Future Lang & Tech: C" : "FutureLangTechC",
"Future Lang & Tech: C++" : "FutureLangTechC++",
"Future Lang & Tech: C++11" : "FutureLangTechC++11",
"Future Lang & Tech: C#" : "FutureLangTechC#",
"Future Lang & Tech: Cassandra" : "FutureLangTechCassandra",
"Future Lang & Tech: CoffeeScript" : "FutureLangTechCoffeeScript",
"Future Lang & Tech: Cordova" : "FutureLangTechCordova",
"Future Lang & Tech: Clojure" : "FutureLangTechClojure",
"Future Lang & Tech: Cloud" : "FutureLangTechCloud",
"Future Lang & Tech: Dart" : "FutureLangTechDart",
"Future Lang & Tech: F#" : "FutureLangTechF#",
"Future Lang & Tech: Go" : "FutureLangTechGo",
"Future Lang & Tech: Hadoop" : "FutureLangTechHadoop",
"Future Lang & Tech: Haskell" : "FutureLangTechHaskell",
"Future Lang & Tech: iOS" : "FutureLangTechiOS",
"Future Lang & Tech: Java" : "FutureLangTechJava",
"Future Lang & Tech: JavaScript" : "FutureLangTechJavaScript",
"Future Lang & Tech: LAMP" : "FutureLangTechLAMP",
"Future Lang & Tech: Matlab" : "FutureLangTechMatlab",
"Future Lang & Tech: MongoDB" : "FutureLangTechMongoDB",
"Future Lang & Tech: Node.js" : "FutureLangTechNode.js",
"Future Lang & Tech: Objective-C" : "FutureLangTechObjective-C",
"Future Lang & Tech: Perl" : "FutureLangTechPerl",
"Future Lang & Tech: PHP" : "FutureLangTechPHP",
"Future Lang & Tech: Python" : "FutureLangTechPython",
"Future Lang & Tech: R" : "FutureLangTechR",
"Future Lang & Tech: Redis" : "FutureLangTechRedis",
"Future Lang & Tech: Ruby" : "FutureLangTechRuby",
"Future Lang & Tech: Rust" : "FutureLangTechRust",
"Future Lang & Tech: Salesforce" : "FutureLangTechSalesforce",
"Future Lang & Tech: Scala" : "FutureLangTechScala",
"Future Lang & Tech: Sharepoint" : "FutureLangTechSharepoint",
"Future Lang & Tech: Spark" : "FutureLangTechSpark",
"Future Lang & Tech: SQL" : "FutureLangTechSQL",
"Future Lang & Tech: SQL Server" : "FutureLangTechSQLServer",
"Future Lang & Tech: Swift" : "FutureLangTechSwift",
"Future Lang & Tech: Visual Basic" : "FutureLangTechVisualBasic",
"Future Lang & Tech: Windows Phone" : "FutureLangTechWindowsPhone",
"Future Lang & Tech: Wordpress" : "FutureLangTechWordpress",
"Future Lang & Tech: Write-In" : "FutureLangTechWrite-In",
"Training & Education: No formal training" : "TrainingEdNoFormal",
"Training & Education: On the job" : "TrainingEdOnTheJob",
"Training & Education: Boot camp or night school" : "TrainingEdBootCamp",
"Training & Education: Online Class" : "TrainingEdOnlineClass",
"Training & Education: Mentorship" : "TrainingEdMentorship",
"Training & Education: Industry certification" : "TrainingEdIndustryCert",
"Training & Education: Some college, but no CS degree" : "TrainingEdSomeCollNoCS",
"Training & Education: BS in CS" : "TrainingEdBSinCS",
"Training & Education: Masters in CS" : "TrainingEdMastersinCS",
"Training & Education: PhD in CS" : "TrainingEdPhDinCS",
"Training & Education: Other" : "TrainingEdOther",
"Compensation" : "Compensation",
"Compensation: midpoint" : "CompensationMidPt",
"Employment Status" : "EmploymentStatus",
"Industry" : "Industry",
"Job Satisfaction" : "JobSatisfaction",
"Purchasing Power" : "PurchasingPower",
"Remote Status" : "RemoteStatus",
"Changed Jobs in last 12 Months" : "ChangedJobsInLastYear",
"Open to new job opportunities" : "CurrLookingNewJob",
"Most important aspect of new job opportunity: Salary" : "AssessJobSalary",
"Most important aspect of new job opportunity: Equity" : "AssessJobEquity",
"Most important aspect of new job opportunity: Important decisions" : "AssessJobImpDec",
"Most important aspect of new job opportunity: Health insurance" : "AssessJobHealthIns",
"Most important aspect of new job opportunity: Industry" : "AssessJobIndustry",
"Most important aspect of new job opportunity: Tech stack" : "AssessJobTech",
"Most important aspect of new job opportunity: Company size" : "AssessJobCompSize",
"Most important aspect of new job opportunity: Company stage" : "AssessJobCompStage",
"Most important aspect of new job opportunity: Work - Life balance" : "AssessJobWorkLife",
"Most important aspect of new job opportunity: Advancement" : "AssessJobAdvance",
"Most important aspect of new job opportunity: Job title" : "AssessJobTitle",
"Most important aspect of new job opportunity: Office location" : "AssessJobLocation",
"Most important aspect of new job opportunity: Quality of colleagues" : "AssessJobQualColleagues",
"Most important aspect of new job opportunity: Company culture" : "AssessJobCompCult",
"Most important aspect of new job opportunity: Company reputation" : "AssessJobCompRep",
"Most important aspect of new job opportunity: Building something that matters" : "AssessJobBldgSmthgImp",
"Most important aspect of new job opportunity: Remote working" : "AssessJobRemote",
"Most important aspect of new job opportunity: Flexible work options" : "AssessJobFlexWork",
"How important is remote when evaluating new job opportunity?" : "ImpOfRemote",
"Most annoying about job search: Finding time" : "JobSearchAnnoyFindTime",
"Most annoying about job search: Finding job I'm qualified for" : "JobSearchAnnoyFindQualfJob",
"Most annoying about job search: Finding interesting job" : "JobSearchAnnoyFindIntrstJob",
"Most annoying about job search: Interesting companies rarely respond" : "JobSearchAnnoyNoResp",
"Most annoying about job search: Writing and updating CV" : "JobSearchAnnoyUpdatingCV",
"Most annoying about job search: Taking time off work to interview" : "JobSearchAnnoyTimeOffInterv",
"Most annoying about job search: The Interview" : "JobSearchAnnoyInterview",
"How often contacted by recruiters" : "FreqOfCntctByRecruitrs",
"Perception of recruiter contact" : "PerceptionOfRecruitrs",
"Perception of contact form: Email" : "PerceptionOfCntctEmail",
"Perception of contact form: LinkedIn" : "PerceptionOfCntctLinkedIn",
"Perception of contact form: Xing" : "PerceptionOfCntctXing",
"Perception of contact form: Phone" : "PerceptionOfCntctPhone",
"Perception of contact form: Stack Overflow Careers" : "PerceptionOfCntctStckOvrflw",
"Perception of contact form: Twitter" : "PerceptionOfCntctTwtr",
"Perception of contact form: Facebook" : "PerceptionOfCntctFB",
"Appealing message traits: Message is personalized" : "AppealingMsgPersonal",
"Appealing message traits: Code or projects mentioned" : "AppealingMsgCode",
"Appealing message traits: Stack Overflow activity mentioned" : "AppealingMsgStckOvrflw",
"Appealing message traits: Team described" : "AppealingMsgTeam",
"Appealing message traits: Company culture described" : "AppealingMsgCompCult",
"Appealing message traits: Salary information" : "AppealingMsgSalaryInfo",
"Appealing message traits: Benefits & Perks" : "AppealingMsgBenefits",
"Appealing message traits: Stack Overflow Company Page" : "AppealingMsgStckOvrflwComp",
"Most urgent info about job opportunity: Salary" : "MostUrgJobInfoSalary",
"Most urgent info about job opportunity: Benefits" : "MostUrgJobInfoBenefits",
"Most urgent info about job opportunity: Company name" : "MostUrgJobInfoCompName",
"Most urgent info about job opportunity: Tech stack" : "MostUrgJobInfoTechStack",
"Most urgent info about job opportunity: Office location" : "MostUrgJobInfoOfficeLoc",
"Most urgent info about job opportunity: Job title" : "MostUrgJobInfoJobTitle",
"Most urgent info about job opportunity: Colleagues" : "MostUrgJobInfoColleagues",
"Most urgent info about job opportunity: Product details" : "MostUrgJobInfoProduct",
"Who do you want to communicate with about a new job opportunity: Headhunter" : "DesiredCntctNewJobHeadHunter",
"Who do you want to communicate with about a new job opportunity: In-house recruiter" : "DesiredCntctNewJobInHouseRecr",
"Who do you want to communicate with about a new job opportunity: In-house tech recruiter" : "DesiredCntctNewJobInHouseTechRecr",
"Who do you want to communicate with about a new job opportunity: Manager" : "DesiredCntctNewJobMngr",
"Who do you want to communicate with about a new job opportunity: Developer" : "DesiredCntctNewJobDvlpr",
"How can companies improve interview process: More live code" : "ImprvmntToIntrvwMoreLiveCode",
"How can companies improve interview process: Flexible interview schedule" : "ImprvmntToIntrvwFlxbleIntrvw",
"How can companies improve interview process: Remote interviews" : "ImprvmntToIntrvwRemoteIntrvw",
"How can companies improve interview process: Introduce me to boss" : "ImprvmntToIntrvwMeetBoss",
"How can companies improve interview process: Introduce me to team" : "ImprvmntToIntrvwMeetTeam",
"How can companies improve interview process: Gimme coffee" : "ImprvmntToIntrvwCoffee",
"How can companies improve interview process: Show me workplace" : "ImprvmntToIntrvwSeeWorkplce",
"How can companies improve interview process: Fewer brainteasers" : "ImprvmntToIntrvwFewerPuzzles",
"How can companies improve interview process: Better preparation" : "ImprvmntToIntrvwBetterPrep",
"Why try Stack Overflow Careers: No spam" : "WhyStckOvrflwCareersNoSpam",
"Why try Stack Overflow Careers: Jobs site for programmers" : "WhyStckOvrflwCareersJobsSites",
"Why try Stack Overflow Careers: Selection of revelant jobs" : "WhyStckOvrflwCareersJobSelect",
"Why try Stack Overflow Careers: Showcase Stack Overflow activity" : "WhyStckOvrflwCareersStckOvrShwcase",
"Why try Stack Overflow Careers: Jobs are on Stack Overflow" : "WhyStckOvrflwCareersManyJobs",
"Why try Stack Overflow Careers: Other" : "WhyStckOvrflwCareersOther",
"How many caffeinated beverages per day?" : "NumCaffBevPerDay",
"How many hours programming as hobby per week?" : "NumHoursPrgrmHobbyPerWeek",
"How frequently land on or read Stack Overflow" : "HowFreqAtStackOvrflw",
"Preferred text editor" : "PreferredTextEditor",
"Preferred text editor: write-in" : "PreferredTextEditorWriteIn",
"Prefered IDE theme" : "PreferredIDETheme",
"Source control used: Git" : "SourceCntrlUsedGit",
"Source control used: Mercurial" : "SourceCntrlUsedHg",
"Source control used: SVN" : "SourceCntrlUsedSVN",
"Source control used: CVS" : "SourceCntrlUsedCVS",
"Source control used: Perforce" : "SourceCntrlUsedPerforce",
"Source control used: TFS" : "SourceCntrlUsedTFS",
"Source control used: DCVS" : "SourceCntrlUsedDCVS",
"Source control used: Bitkeeper" : "SourceCntrlUsedBitkeeper",
"Source control used: Legacy / Custom" : "SourceCntrlUsedCustom",
"Source control used: I don't use source control" : "SourceCntrlUsedNone",
"Source control used: write-in" : "SourceCntrlUsedWriteIn",
"Prefered Source Control" : "PreferredSourceControl",
"Prefered Source Control: write-in" : "PreferredSourceControlWriteIn",
"Why use Stack Overflow: Help for job" : "WhyUseStckOvrflwHelpforJob",
"Why use Stack Overflow: To give help" : "WhyUseStckOvrflwGiveHelp",
"Why use Stack Overflow: Can't do job without it" : "WhyUseStckOvrflwNeedForJob",
"Why use Stack Overflow: Maintain online presence" : "WhyUseStckOvrflwOnlinePresnce",
"Why use Stack Overflow: Demonstrate expertise" : "WhyUseStckOvrflwDemoExp",
"Why use Stack Overflow: Communicate with others" : "WhyUseStckOvrflwCommunicate",
"Why use Stack Overflow: Receive help on personal projects" : "WhyUseStckOvrflwHelpOnProj",
"Why use Stack Overflow: Love to learn" : "WhyUseStckOvrflwLoveToLearn",
"Why use Stack Overflow: I don't use Stack Overflow" : "WhyUseStckOvrflwDoNotUse",
"How often are Stack Overflow's answers helpful" : "HowFreqStckOvrflwHelpful",
"Why answer: Help a programmer in need" : "WhyAnswerQHelpPrgrmr",
"Why answer: Help future programmers" : "WhyAnswerQHelpFuturePrgrmr",
"Why answer: Demonstrate expertise" : "WhyAnswerQDemoExp",
"Why answer: Self promotion" : "WhyAnswerQSelfPromo",
"Why answer: Sense of responsibility to developers" : "WhyAnswerQSenseOfResp",
"Why answer: No idea" : "WhyAnswerQDoNotKnow",
"Why answer: I don't answer and I don't want to" : "WhyAnswerQNoAnsDoNotWant",
"Why answer: I don't answer but I want to" : "WhyAnswerQNoAnsWantTo",
}